#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

show_usage() {
    echo "Usage: kiwi_set [key] [file]"
    exit 1
}

# Check argument count
if [ "$#" -ne 2 ]; then
    show_usage
fi


# Initalize database file is not already
sqlite3 "$SQLITE3KVDB" "CREATE TABLE IF NOT EXISTS config(name TEXT NOT NULL UNIQUE, value BLOB);"

# Set key-value pair
sqlite3 "$SQLITE3KVDB" "INSERT INTO config(name, value) VALUES ('$1', readfile('$2')) ON CONFLICT(name) DO UPDATE SET value=excluded.value;"
