#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

show_usage() {
    echo "Usage: kiwi_get [key] [filename]"
    exit 1
}

# Check argument count
if [ "$#" -ne 2 ]; then
    show_usage
fi


# Initalize database file is not already
sqlite3 "$SQLITE3KVDB" "CREATE TABLE IF NOT EXISTS config(name TEXT NOT NULL UNIQUE, value BLOB);"

# Get value from key
sqlite3 "$SQLITE3KVDB" "SELECT writefile('$2',value) FROM CONFIG where name='$1';"
